packages:
  - apps/admin
  - apps/web
  - packages/*

allowBuilds:
  esbuild: true
  vue-demi: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - vite@8.2.2
overrides:
  '@novelia/auth-api': github:auto-novel/auth#730c065bee8062946738b1fb2ff2f28369b78b8a&path:packages/auth-api
