packages:
  - apps/admin
  - apps/web
  - packages/*

allowBuilds:
  esbuild: true
  vue-demi: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - vite@8.2.2
overrides:
  '@novelia/auth-api': github:auto-novel/auth#490e384368f018e670aa9cf8a30c8bb1d8512865&path:packages/auth-api
