packages:
  - apps/admin
  - apps/web
  - packages/*

allowBuilds:
  esbuild: true
  vue-demi: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - vite@8.2.2
overrides:
  '@novelia/auth-api': github:auto-novel/auth#16cde8bd1b2b329bd3e3c272d37c153d4bbd4c38&path:packages/auth-api
