//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserBlacklist = newUserBlacklistTable("public", "user_blacklist", "")

type userBlacklistTable struct {
	postgres.Table

	// Columns
	UserID        postgres.ColumnInteger
	BlockedUserID postgres.ColumnInteger
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserBlacklistTable struct {
	userBlacklistTable

	EXCLUDED userBlacklistTable
}

// AS creates new UserBlacklistTable with assigned alias
func (a UserBlacklistTable) AS(alias string) *UserBlacklistTable {
	return newUserBlacklistTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserBlacklistTable with assigned schema name
func (a UserBlacklistTable) FromSchema(schemaName string) *UserBlacklistTable {
	return newUserBlacklistTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserBlacklistTable with assigned table prefix
func (a UserBlacklistTable) WithPrefix(prefix string) *UserBlacklistTable {
	return newUserBlacklistTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserBlacklistTable with assigned table suffix
func (a UserBlacklistTable) WithSuffix(suffix string) *UserBlacklistTable {
	return newUserBlacklistTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserBlacklistTable(schemaName, tableName, alias string) *UserBlacklistTable {
	return &UserBlacklistTable{
		userBlacklistTable: newUserBlacklistTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newUserBlacklistTableImpl("", "excluded", ""),
	}
}

func newUserBlacklistTableImpl(schemaName, tableName, alias string) userBlacklistTable {
	var (
		UserIDColumn        = postgres.IntegerColumn("user_id")
		BlockedUserIDColumn = postgres.IntegerColumn("blocked_user_id")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{UserIDColumn, BlockedUserIDColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{CreatedAtColumn}
	)

	return userBlacklistTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:        UserIDColumn,
		BlockedUserID: BlockedUserIDColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
